# -*- coding: utf-8 -*-
"""assignment3.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19i5ZqIE8dPCQZIhmjlemAdbFyzJiq1Fb

ANANYA V R

ASSIGNMENT 3

Part 1: Basic Slicing

1. Introduction to Slicing:

a. Given a string s = "Hello, World!", slice and print the following:
i. The entire string.
ii. The first 5 characters.
iii. The last 5 characters.
iv. The string excludes the first and last characters.
v. Every second character in the string.
"""

s = "Hello, World!"
print(s)
print(s[:5])
print(s[-5:])
print(s[1:-1])
print(s[::2])

"""2. Slicing with Negative Indices:

a. Use negative indices to slice and print the following from the string
s:
A)The last 3 characters.
B) All characters except the last 2.
C) The string reversed.
"""

print(s[-3:])
print(s[:-2])
print(s[::-1])

"""Part 2: Advanced Slicing

1. Slicing Substrings:

a. Given a string sentence = "The quick brown fox jumps over the lazy
dog", slice and print the following:

i. The word "quick".
ii. The word "lazy".
iii. The words "brown fox jumps"
"""

a= "The quick brown fox jumps over the lazy dog"
print(a[4:9])
print(a[-8:-4])
print(a[10:26])

"""2. Step Slicing:

a. Use step slicing to print the following from the string s:

i. Every third character.
ii. Every third character starting from the second character.
iii. The string reversed, stepping by 2.
"""

s = "Hello, World!"
print(s[::3])
print(s[1::3])
print(s[::-2])

"""Part 3: Practical Application

1. Extracting Information:

a. Given a string data = "2024-09-01,Sunny,25°C", extract and print
the following:

i. The date.
ii. The weather condition.
iii. The temperature
"""

data = "2024-09-01,Sunny,25°C"
date = data.split(",")[0]
print("Date:", date)
weather = data.split(",")[1]
print("Weather:", weather)
temperature = data.split(",")[2]
print("Temperature:", temperature)

"""2. Reformatting Strings:

i. Given a string phone_number = "(123) 456-7890", reformat
it to ‘123-456-7890’
"""

phone_number = "(123) 456-7890"
new_number = phone_number.replace("(", "").replace(")", "-").replace(" ", "")
print(new_number)

"""Part 4: Questions based on string methods

1. Upper and Lower Case Conversion:

i. Given a string s = "Hello, World!", perform the following:
b. Convert the string to all uppercase letters.
c. Convert the string to all lowercase letters.
d. Convert the string to title case.
e. Capitalize the first letter of the string.
"""

s = "Hello, World!"
# b. Convert the string to all uppercase letters.
print(s.upper())
# c. Convert the string to all lowercase letters.
print(s.lower())
# d. Convert the string to title case.
print(s.title())
# e. Capitalize the first letter of the string.
print(s.capitalize())

"""2. Finding Substrings:

Given a string s = "The quick brown fox jumps over the lazy dog",
perform the following:

a. Find the position of the substring "fox".

b. Check if the substring "cat" is in the string.
"""

s = "The quick brown fox jumps over the lazy dog"
position = s.find("fox")
print(position)
if "cat" in s:
  print("Substring 'cat' is found in the string.")
else:
  print("Substring 'cat' is not found in the string.")

"""3. Replacing Substrings:

Given a string s = "The quick brown fox jumps over the lazy dog",
perform the following:

a. Replace "fox" with "cat".

b. Replace all spaces with underscores.

c. Split the string into a list of words.

d. Split the string by the letter 'o'.
"""

s = "The quick brown fox jumps over the lazy dog"
new_s = s.replace("fox", "cat")
print(new_s)
new_s = s.replace(" ", "_")
print(new_s)
words = s.split()
print(words)
parts = s.split("o")
print(parts)

"""4.Joining Strings:

Given a list of words
words = ["The", "quick", "brown", "fox"],
perform the following:

a. Join the words with spaces.
b. Join the words with hyphens
"""

a = ["The", "quick", "brown", "fox"]
a_spaces = " ".join(a)
print(a_spaces)
a_hyphens = "-".join(a)
print(a_hyphens)